# Generated by Django 4.2.16 on 2025-08-23 22:56

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base
import tenants.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djstripe', '0012_2_8'),
    ]

    operations = [
        migrations.CreateModel(
            name='MspCompany',
            fields=[
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('address_1', models.CharField(max_length=50)),
                ('address_2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('United States', 'United States'), ('Canada', 'Canada')], max_length=50)),
                ('timezone', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, null=True, validators=[tenants.models.validate_phone_or_fax])),
                ('fax', models.CharField(blank=True, null=True, validators=[tenants.models.validate_phone_or_fax])),
                ('company_name', models.CharField(max_length=60)),
                ('industry_type', models.CharField(choices=[('', 'Select industry type'), ('Agriculture', 'Agriculture'), ('Construction', 'Construction'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Finance & Insurance', 'Finance &  Insurance'), ('Healthcare', 'Healthcare'), ('Higher Education', 'Higher  Education'), ('Hospitality', 'Hospitality'), ('Information Technology', 'Information  Technology'), ('Manufacturing', 'Manufacturing'), ('Nonprofit', 'Nonprofit'), ('Professional Services', 'Professional  Services'), ('Real Estate', 'Real  Estate'), ('Retail', 'Retail'), ('Telecommunications', 'Telecommunications'), ('Transportation', 'Transportation'), ('Utilities', 'Utilities'), ('Wholesale', 'Wholesale')], max_length=68)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('owner_name', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/company')),
                ('subscription_tier', models.CharField(choices=[('starter', 'Starter Tier'), ('growth', 'Growth Tier'), ('innovator', 'Innovator Tier')], default='starter', help_text='Current subscription tier', max_length=20)),
                ('company_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('enable_entra_id_auth', models.BooleanField(default=False, help_text='Enable Microsoft Entra ID (Azure AD) authentication for this tenant')),
                ('entra_id_tenant_id', models.CharField(blank=True, help_text="Client's Microsoft Entra ID Tenant ID (Directory ID)", max_length=255, null=True)),
                ('entra_id_client_id', models.CharField(blank=True, help_text="Client's Microsoft Entra ID Application (Client) ID", max_length=255, null=True)),
                ('entra_id_client_secret', models.CharField(blank=True, help_text="Client's Microsoft Entra ID Application Client Secret", max_length=255, null=True)),
                ('subscription', models.ForeignKey(blank=True, help_text="The team's Stripe Subscription object, if it exists", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.mspcompany')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
