# Generated by Django 5.2.3 on 2025-08-02 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0012_2_8'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mspcompany',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text="The team's Stripe Subscription object, if it exists", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.subscription'),
        ),
        migrations.AddField(
            model_name='mspcompany',
            name='subscription_tier',
            field=models.CharField(choices=[('starter', 'Starter Tier'), ('growth', 'Growth Tier'), ('innovator', 'Innovator Tier')], default='starter', help_text='Current subscription tier', max_length=20),
        ),
    ]
