# Generated by Django 5.2.3 on 2025-07-04 15:46

import django.contrib.postgres.fields
import django.db.models.deletion
import recurrence.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('Danger', 'Danger'), ('Dark', 'Dark'), ('Info', 'Info'), ('Primary', 'Primary'), ('Success', 'Success'), ('Warning', 'Warning')], max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=145, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('event_last_date', models.DateField(blank=True, null=True)),
                ('repeating', models.BooleanField(blank=True, default=False, null=True)),
                ('repeat_interval', models.IntegerField(blank=True, null=True)),
                ('repeat_frequency', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=20, null=True)),
                ('repeat_by_weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'MONDAY'), (1, 'TUESDAY'), (2, 'WEDNESDAY'), (3, 'THURSDAY'), (4, 'FRIDAY'), (5, 'SATURDAY'), (6, 'SUNDAY')]), blank=True, default=list, null=True, size=None)),
                ('recurrence', recurrence.fields.RecurrenceField(blank=True, null=True, verbose_name='Recurrence')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_creator', to=settings.AUTH_USER_MODEL)),
                ('guests', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
