# Generated by Django 4.2.16 on 2025-08-31 03:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendar_event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevents',
            name='mandatory_invites',
            field=models.ManyToManyField(blank=True, related_name='mandatory_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarevents',
            name='optional_invites',
            field=models.ManyToManyField(blank=True, related_name='optional_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calendarevents',
            name='guests',
            field=models.ManyToManyField(blank=True, related_name='event_guests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calendarevents',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevents',
            name='repeat_frequency',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BI_WEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly'), ('ANNUALLY', 'Annually'), ('CUSTOM', 'Custom')], max_length=20, null=True),
        ),
    ]
