# Generated by Django 4.2.16 on 2025-08-23 22:56

import accounts.models
import apps.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIIntegrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(blank=True, choices=[('Apple', 'Apple'), ('OpenAI', 'OpenAI'), ('Google', 'Google'), ('Other', 'Other')], max_length=30, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API Integration',
                'verbose_name_plural': 'API Integrations',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(blank=True, max_length=50, null=True)),
                ('address_2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, choices=[('United States', 'United States'), ('Canada', 'Canada')], max_length=50, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, null=True, validators=[accounts.models.validate_phone_or_fax])),
                ('fax', models.CharField(blank=True, null=True, validators=[accounts.models.validate_phone_or_fax])),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.models.client_directory_path)),
                ('threshold', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=150)),
                ('contact_first', models.CharField(max_length=50)),
                ('contact_last', models.CharField(max_length=50)),
                ('industry', models.CharField(blank=True, choices=[('', 'Select industry type'), ('Agriculture', 'Agriculture'), ('Construction', 'Construction'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Finance & Insurance', 'Finance &  Insurance'), ('Healthcare', 'Healthcare'), ('Higher Education', 'Higher  Education'), ('Hospitality', 'Hospitality'), ('Information Technology', 'Information  Technology'), ('Manufacturing', 'Manufacturing'), ('Nonprofit', 'Nonprofit'), ('Professional Services', 'Professional  Services'), ('Real Estate', 'Real  Estate'), ('Retail', 'Retail'), ('Telecommunications', 'Telecommunications'), ('Transportation', 'Transportation'), ('Utilities', 'Utilities'), ('Wholesale', 'Wholesale')], max_length=50, null=True)),
                ('website', models.URLField(blank=True, max_length=150, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Crm Companies',
            },
        ),
        migrations.CreateModel(
            name='ClientCompanyFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.models.client_directory_files_path)),
                ('upload_date', models.DateField(auto_now_add=True)),
            ],
            bases=(models.Model, apps.models.File),
        ),
        migrations.CreateModel(
            name='ClientLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headquarter', models.BooleanField(blank=True, default=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('address_1', models.CharField(max_length=80)),
                ('address_2', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=33)),
                ('phone', models.CharField(blank=True, null=True, validators=[apps.models.validate_phone_or_fax])),
                ('email', models.EmailField(max_length=150)),
                ('zip', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Client Location',
                'verbose_name_plural': 'Client Locations',
                'ordering': ['-client'],
            },
        ),
        migrations.CreateModel(
            name='ClientTeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('title', models.CharField(blank=True, max_length=25, null=True)),
                ('work_phone', models.CharField(blank=True, null=True, validators=[apps.models.validate_phone_or_fax])),
                ('work_email', models.EmailField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Client Team Member',
                'verbose_name_plural': 'Client Team Members',
                'ordering': ['-first_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Client User',
                'verbose_name_plural': 'Client Users',
            },
        ),
        migrations.CreateModel(
            name='ClientWorkTypeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Client Work Type Rate',
                'verbose_name_plural': 'Client Work Type Rates',
            },
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.URLField()),
                ('info', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('hours', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
            },
        ),
        migrations.CreateModel(
            name='LeadCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(blank=True, max_length=50, null=True)),
                ('address_2', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, choices=[('United States', 'United States'), ('Canada', 'Canada')], max_length=50, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, null=True, validators=[accounts.models.validate_phone_or_fax])),
                ('fax', models.CharField(blank=True, null=True, validators=[accounts.models.validate_phone_or_fax])),
                ('logo', models.ImageField(blank=True, default=apps.models.random_img_leads, null=True, upload_to=apps.models.lead_directory_path)),
                ('name', models.CharField(max_length=150)),
                ('contact_first', models.CharField(max_length=50)),
                ('contact_last', models.CharField(max_length=50)),
                ('industry', models.CharField(blank=True, choices=[('', 'Select industry type'), ('Agriculture', 'Agriculture'), ('Construction', 'Construction'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Finance & Insurance', 'Finance &  Insurance'), ('Healthcare', 'Healthcare'), ('Higher Education', 'Higher  Education'), ('Hospitality', 'Hospitality'), ('Information Technology', 'Information  Technology'), ('Manufacturing', 'Manufacturing'), ('Nonprofit', 'Nonprofit'), ('Professional Services', 'Professional  Services'), ('Real Estate', 'Real  Estate'), ('Retail', 'Retail'), ('Telecommunications', 'Telecommunications'), ('Transportation', 'Transportation'), ('Utilities', 'Utilities'), ('Wholesale', 'Wholesale')], max_length=50, null=True)),
                ('website', models.URLField(blank=True, max_length=150, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lead Company',
                'verbose_name_plural': 'Leads Companies',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='LeadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.models.lead_files_directory_path)),
                ('upload_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead File',
                'verbose_name_plural': 'Lead Files',
                'ordering': ['-upload_date'],
            },
            bases=(models.Model, apps.models.File),
        ),
        migrations.CreateModel(
            name='LeadOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_contact', models.DateField()),
                ('attempts', models.IntegerField(default=0)),
                ('conversion_rate', models.FloatField(default=0.0)),
                ('promo', models.TextField()),
                ('converted_date', models.DateField(blank=True, null=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead Opportunity',
                'verbose_name_plural': 'Lead Opportunities',
                'ordering': ['-lead'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('private', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Project Comment',
                'verbose_name_plural': 'Project Comments',
                'ordering': ['-date_added'],
                'permissions': [('view_own_project_comments', 'Can view their own project comments'), ('delete_own_project_comments', 'Can delete their own project comments')],
            },
        ),
        migrations.CreateModel(
            name='ProjectCommentReplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('private', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Project Comment Reply',
                'verbose_name_plural': 'Project Comment Replies',
                'ordering': ['-date_added'],
                'permissions': [('view_own_project_comment_replies', 'Can view their own project comment replies'), ('delete_own_project_comments_replies', 'Can delete their own project comments replies')],
            },
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.models.project_directory_files_path)),
                ('upload_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project File',
                'verbose_name_plural': 'Project Files',
                'ordering': ['-upload_date'],
            },
            bases=(models.Model, apps.models.File),
        ),
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.models.project_directory_path)),
                ('name', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField(blank=True, default='Please add Project description... ', null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Scheduled', 'Scheduled'), ('Follow Up', 'Follow Up'), ('Reviewing', 'Reviewing'), ('Observing', 'Inprogress'), ('Waiting on Client', 'Waiting on Client'), ('Waiting on Vendor', 'Waiting on Vendor'), ('Waiting on Client', 'Waiting on Client'), ('Postponed', 'Postponed'), ('Post to Call Waiting', 'Post to Call Waiting'), ('Completed', 'Completed')], max_length=50, null=True)),
                ('priority', models.CharField(blank=True, choices=[('Emergency', 'Emergency'), ('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-name'],
                'permissions': [('view_own_projects', 'Can view their own projects'), ('assign_own_project', 'Can assign themselves to a project'), ('assign_other_project', 'Can assign others to a project')],
            },
        ),
        migrations.CreateModel(
            name='QuickBooksCustomer',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'QuickBooks Customer',
                'verbose_name_plural': 'QuickBooks Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickBooksInvoice',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('docNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'QuickBooks Invoice',
                'verbose_name_plural': 'QuickBooks Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickBooksToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(max_length=1000)),
                ('realm_id', models.CharField(max_length=1000, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_in', models.IntegerField(default=0)),
                ('is_refresh_token_replaced', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'QuickBooks Token',
                'verbose_name_plural': 'QuickBooks Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('private', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ticket Comment',
                'verbose_name_plural': 'Ticket Comments',
                'ordering': ['-date_added'],
                'permissions': [('view_own_ticket_comments', 'Can view their own ticket comments'), ('delete_own_ticket_comments', 'Can delete their own ticket comments')],
            },
        ),
        migrations.CreateModel(
            name='WebviewIntegrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, default=apps.models.random_img_webviews, null=True, upload_to='images/webview')),
                ('favorite', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketList',
            fields=[
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.models.ticket_directory_path)),
                ('identifier', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', ckeditor.fields.RichTextField(blank=True, default='Add description for Ticket: ', null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('ticket_type', models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Scheduled', 'Scheduled'), ('Postponed', 'Postponed'), ('Waiting on Client', 'Waiting on Client'), ('Waiting on Vendor', 'Waiting on Vendor'), ('Follow-Up', 'Follow-Up'), ('Need to Post', 'Need to Post'), ('Completed', 'Completed'), ('Closed', 'Closed')], max_length=50)),
                ('priority', models.CharField(blank=True, choices=[('Emergency', 'Emergency'), ('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium')], max_length=10, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to=apps.models.ticket_directory_path)),
                ('assignment', models.ManyToManyField(to='accounts.technicianuser')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.clientcompany')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.projectlist')),
                ('tag', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-identifier'],
                'permissions': [('view_own_ticketlist', 'Can view own tickets'), ('view_ticket_stats', 'Can view ticket statistics'), ('view_estimated_work', 'Can view estimated work'), ('assign_own_ticketlist', 'Can assign themselves to a ticket'), ('assign_other_ticket', 'Can assign others to a ticket'), ('complete_ticketlist', 'Can mark a ticket as Completed'), ('close_ticketlist', 'Can mark a ticket as Closed')],
            },
        ),
        migrations.CreateModel(
            name='TicketFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.models.ticket_directory_files_path)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.ticketlist')),
            ],
            bases=(models.Model, apps.models.File),
        ),
        migrations.CreateModel(
            name='TicketCommentReplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('private', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.ticketcomment')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.ticketlist')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket Comment Reply',
                'verbose_name_plural': 'Ticket Comment Replies',
                'ordering': ['-date_added'],
                'permissions': [('view_own_ticket_comments_replies', 'Can view their own ticket comments replies'), ('delete_own_ticket_comments_replies', 'Can delete their own ticket comments replies')],
            },
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.ticketlist'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TechnicianLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.BigIntegerField(default=0)),
                ('is_tracked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.technicianuser')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_labor', to='apps.ticketlist')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_labor_stats', 'Can view labor statistics')],
            },
        ),
        migrations.CreateModel(
            name='SalesRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('New Sale', 'New Sale'), ('Proposal Created', 'Proposal Created'), ('Proposal Sent', 'Proposal Sent'), ('Proposal Executed', 'Proposal Executed'), ('Sale Closed', 'Sale Closed')], max_length=45)),
                ('value', models.FloatField(default=0.0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.clientcompany')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.clientteammembers')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.technicianuser')),
            ],
            options={
                'ordering': ['-create_date'],
            },
        ),
    ]
