# Generated by Django 5.2.3 on 2025-07-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcompany',
            name='main_tech',
        ),
    ]
