# Generated by Django 4.2.16 on 2025-08-23 22:56

import apps.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
        ('apps', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbookstoken',
            name='mspcompany',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenants.mspcompany'),
        ),
        migrations.AddField(
            model_name='quickbooksinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.quickbookscustomer'),
        ),
        migrations.AddField(
            model_name='projectlist',
            name='assignment',
            field=models.ManyToManyField(to='accounts.technicianuser'),
        ),
        migrations.AddField(
            model_name='projectlist',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.clientcompany'),
        ),
        migrations.AddField(
            model_name='projectlist',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='projectlist',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='projects', to='apps.ticketlist'),
        ),
        migrations.AddField(
            model_name='projectfiles',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.projectlist'),
        ),
        migrations.AddField(
            model_name='projectcommentreplies',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apps.projectcomment'),
        ),
        migrations.AddField(
            model_name='projectcommentreplies',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.projectlist'),
        ),
        migrations.AddField(
            model_name='projectcommentreplies',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.projectlist'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadopportunity',
            name='assigned_to',
            field=models.ForeignKey(on_delete=models.SET(apps.models.set_admin_user), related_name='maintainer', to='accounts.technicianuser'),
        ),
        migrations.AddField(
            model_name='leadopportunity',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET(apps.models.set_admin_user), related_name='creator', to='accounts.technicianuser'),
        ),
        migrations.AddField(
            model_name='leadopportunity',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.leadcompany'),
        ),
        migrations.AddField(
            model_name='leadfiles',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.leadcompany'),
        ),
        migrations.AddField(
            model_name='leadcompany',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.technicianuser'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='apps.ticketlist'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.clientcompany'),
        ),
        migrations.AddField(
            model_name='clientworktyperate',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_type_rates', to='apps.clientcompany'),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='auth_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='apps.clientcompany'),
        ),
        migrations.AddField(
            model_name='clientteammembers',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.clientcompany'),
        ),
        migrations.AddField(
            model_name='clientlocations',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.clientcompany'),
        ),
        migrations.AddField(
            model_name='clientcompanyfiles',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.clientcompany'),
        ),
        migrations.AddField(
            model_name='clientcompany',
            name='main_tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.technicianuser'),
        ),
        migrations.AddField(
            model_name='clientcompany',
            name='quickbooks_customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='msp_client', to='apps.quickbookscustomer'),
        ),
        migrations.AddField(
            model_name='clientcompany',
            name='quickbooks_invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='msp_client', to='apps.quickbooksinvoice'),
        ),
        migrations.AlterUniqueTogether(
            name='clientworktyperate',
            unique_together={('client', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='clientuser',
            unique_together={('auth_user',)},
        ),
    ]
