# Generated by Django 4.2.16 on 2025-08-30 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcompany',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='leadcompany',
            name='industry',
        ),
        migrations.AddField(
            model_name='clientcompany',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('', 'Select grade level'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th'), ('Teacher', 'Teacher'), ('Administration', 'Administration')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leadcompany',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('', 'Select grade level'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th'), ('Teacher', 'Teacher'), ('Administration', 'Administration')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='technicianlabor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
