# Generated by Django 5.2.3 on 2025-07-23 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('apps', '0003_clientcompany_main_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianlabor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.technicianuser'),
        ),
    ]
