# Generated by Django 4.2.16 on 2025-08-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_clientcompany_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcompany',
            name='house',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
