# Generated by Django 5.2.3 on 2025-08-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_technicianlabor_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='projects', to='apps.ticketlist'),
        ),
    ]
